
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/whisn/AppData/Local/Programs/Python/Python39/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:11 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
...
